feature/EventAnalytics rest controller and service to publish webpage…
uPortal-Project/uPortal pull request #2558
Opened 2022-09-18 10:35 UTC by mgillian

… events to uPortal event service

##### Checklist

-   [ ] the [individual contributor license agreement][] is signed
-   [ ] commit message follows [commit guidelines][]
-   [ ] tests are included
-   [ ] documentation is changed or added
-   [ ] [message properties][] have been updated with new phrases
-   [ ] view conforms with [WCAG 2.0 AA][]

##### Description of change

Introduces a controller and service that will handle receiving web page events and processing them through the uPortal events processor.  Initial version handles web page link click events sent via a Javascript post..

[individual contributor license agreement]: https://github.com/Jasig/uPortal/blob/master/CONTRIBUTING.md#individual-contributor-license-agreement
[commit guidelines]: https://github.com/Jasig/uPortal/blob/master/CONTRIBUTING.md#commit
[message properties]: https://github.com/Jasig/uPortal/tree/master/uportal-war/src/main/resources/properties/i18n
[WCAG 2.0 AA]: https://www.w3.org/WAI/WCAG20/quickref/?levels=aaa&technologies=smil%2Cpdf%2Cflash%2Csl

2022-09-19 17:19 UTC, cbeach47 requested changes
Looking good @mgillian !

Comments in line.

For the failing github actions / jobs. You can format the code with `./gradlew goJF`.

2022-09-19 17:19 UTC, cbeach47 commented on uPortal-events/src/main/java/org/apereo/portal/events/rest/AnalyticsPortalEventsController.java
> +	public @ResponseBody Map<String, Object> getAnalytics() {
Should this be removed?

2022-09-19 17:19 UTC, cbeach47 commented on uPortal-events/src/main/java/org/apereo/portal/events/PortalEventFactoryImpl.java
> +        String eventType = InputValidator.validateAsWordCharacters(rawEventType, "String");
I would change the second parameter to 'event type' to help end users locate the issue with the failed request.

2022-09-19 17:19 UTC, cbeach47 commented on uPortal-events/src/main/java/org/apereo/portal/events/rest/AnalyticsPortalEventsService.java
> +public class AnalyticsPortalEventsService {
Could you add an interface here so adopters can overlay this logic with a customized flow in uPortal-start?

2022-09-19 17:19 UTC, cbeach47 commented on uPortal-webapp/src/main/resources/properties/contexts/servlet/analyticsEventsServletContext.xml
> +           http://www.springframework.org/schema/mvc http://www.springframework.org/schema/mvc/spring-mvc-3.2.xsd">
```suggestion
           http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans.xsd
           http://www.springframework.org/schema/context http://www.springframework.org/schema/context/spring-context.xsd
           http://www.springframework.org/schema/mvc http://www.springframework.org/schema/mvc/spring-mvc.xsd">
```

There was an issue a while back with pinning these schemas to a version. Would it work to just leave at the default?

2022-09-20 13:50 UTC, jgribonvald commented
I think it would be good to be able to secure a bit more this part, because as I can see any anonymous request can be done and will be registered. Some attacks can come from here so !
So maybe forbidden guest access, and/or disabling anonymous request, or disabling all of this part from a property could be an option.
For the security part I'm not sure that something more than blocking guest activity can be done.

----------------------------------------------------------------------------------------------------------------------------------------------

Else on my side we have a Servlet that is used by redirects for all other apps that can't be logged from events: https://github.com/GIP-RECIA/recia-uPortal-adds/blob/e6a6c0bd7353d5ec1e1283d4ccd4b146c8bdaffd/src/main/java/fr/recia/portal/events/handlers/EscoStatsLogger.java

And we are processing all logs to obtains stats, we can get session times, number of time a user connected, and times inside apps, etc... All is logged and processed but outside of the portal for better stats.

2022-09-21 19:24 UTC, bjagg commented
Good point, @jgribonvald -- there should be a flag (and defaulted to `true`) to ignore posts to the API where there is no user session. 

Also, would it feasible (and quick) to add a nonce to the page to pass along to the API? This could make the API a little more secure.

2022-09-23 21:01 UTC, bjagg commented
Let's step back from the nonce. I think session tracking for non-guests is enough

2022-09-29 15:53 UTC, cbeach47 approved these changes
👍

2022-10-03 18:50 UTC, merged