Import/Export in the uP5 Manual(#1241)
uPortal-Project/uPortal pull request #2859
Opened 2024-10-01 13:35 UTC by 555vedant

This PR updates the Import/Export tool documentation for uPortal to reflect the new commands in uP5. It replaces outdated commands with the current syntax and usage, ensuring accuracy and clarity. The documentation includes step-by-step instructions and examples to guide users through the Import/Export process. Additionally, it addresses any discrepancies found in the previous version.

2024-10-01 16:31 UTC, 555vedant commented
@ChristianMurphy ready to merge ?

2024-10-01 16:38 UTC, ChristianMurphy commented
@555vedant enhance your calm, give people a chance to review. 🙂

2024-10-01 16:52 UTC, ChristianMurphy commented on docs/import_export/README.md
> +# Import/Export Documentation for uPortal 5
This could be made clearer
```suggestion
# Configuration Data Import and Export Guide for uPortal 5
```

2024-10-01 16:52 UTC, ChristianMurphy commented on docs/import_export/README.md
> +```bash
It's easier to read when there is an empty newline after the heading and before the content
````suggestion

```bash
````

2024-10-01 16:52 UTC, ChristianMurphy commented on docs/import_export/README.md
> +```bash
It's easier to read when there is an empty newline after the heading and before the content
````suggestion

```bash
````

2024-10-01 16:52 UTC, ChristianMurphy commented on docs/import_export/README.md
> +```bash
It's easier to read when there is an empty newline after the heading and before the content
````suggestion

```bash
````

2024-10-01 16:52 UTC, ChristianMurphy commented on docs/import_export/README.md
> +```bash
It's easier to read when there is an empty newline after the heading and before the content
````suggestion
### Import List File (uPortal 4.3+)

```bash
````

2024-10-01 16:52 UTC, ChristianMurphy commented on docs/import_export/README.md
> +```bash
````suggestion
## Deleting Data

```bash
````

2024-10-01 16:52 UTC, ChristianMurphy commented on docs/import_export/README.md
> +
````suggestion
ant data-delete -Dtype={entity-type} [-Dsysid={entity-identifier}]
```

Replace `{entity-type}` with the type of entity you wish to list (e.g., `portlets`, `groups`).
````

2024-10-01 16:52 UTC, ChristianMurphy commented on docs/import_export/README.md
> +```bash
````suggestion
### List Data of a Specific Type

```bash
````

2024-10-01 16:52 UTC, ChristianMurphy commented on docs/import_export/README.md
> +
````suggestion
ant data-list -Dtype={entity-type}
```

Replace `{entity-type}` with the type of entity you wish to list (e.g., `portlets`, `groups`).
````

2024-10-01 16:52 UTC, ChristianMurphy commented on docs/import_export/README.md
> +Logs for Import/Export operations can be found in the `UPORTAL_ROOT/target/data-import-reports` directory. Look for `data-import.txt` for summary reports. If errors occur, individual error report fil
```suggestion
## Import/Export Logs

Logs for Import/Export operations can be found in the `UPORTAL_ROOT/target/data-import-reports` directory. Look for `data-import.txt` for summary reports. If errors occur, individual error report files will also be generated for each failed object.
```

2024-10-01 16:52 UTC, ChristianMurphy commented on docs/import_export/README.md
> +Refer to the logs for detailed error messages if operations fail.
```suggestion
## Troubleshooting

Refer to the logs for detailed error messages if operations fail.
```

2024-10-01 16:52 UTC, ChristianMurphy commented on docs/import_export/README.md
> +- [uPortal 4.1 Importing and Exporting Data](https://apereo.atlassian.net/wiki/spaces/UPM41/pages/103942373/Importing+and+Exporting+data)
```suggestion
## Additional Resources

- [uPortal 4.1 Importing and Exporting Data](https://apereo.atlassian.net/wiki/spaces/UPM41/pages/103942373/Importing+and+Exporting+data)
```

2024-10-01 16:52 UTC, ChristianMurphy commented on docs/import_export/README.md
> +
```suggestion

```

2024-10-01 17:17 UTC, 555vedant commented
@ChristianMurphy  thnx for suggestions

2024-10-01 18:39 UTC, ChristianMurphy commented on docs/import_export/README.md
> +The Import/Export tool in uPortal 5 allows users to transfer configuration data and settings between instances, facilitating data migration and backup.
```suggestion
## Overview

The Import/Export tool in uPortal 5 allows users to transfer configuration data and settings between instances, facilitating data migration and backup.
```

2024-10-01 18:39 UTC, ChristianMurphy commented on docs/import_export/README.md
> +- **IMPORT**: Adds or updates entities from XML files in the portal database.
```suggestion
## Supported Operations

- **IMPORT**: Adds or updates entities from XML files in the portal database.
```

2024-10-01 18:39 UTC, ChristianMurphy commented on docs/import_export/README.md
> +```bash
````suggestion
### List Types

```bash
````

2024-10-01 18:48 UTC, jonathanmtran commented
With uPortal 5, the data import/export tasks are invoked using Gradle. The commands and its parameters are same for the most part, so the documentation needs to be updated to reflect that

2024-10-01 19:48 UTC, 555vedant commented
in this format template is more readable !!

2024-10-01 19:59 UTC, jonathanmtran requested changes
Running `./gradlew :overlays:uPortal:tasks` outputs the following
```
Data tasks
----------
dataDelete - Deletes the specified entity. Requires -Dtype={entity-type} and -Dsysid={id}
dataExport - Creates XML files representing the requested entities and writes them to the specified file system location. Parameters: -Ddir={path-to-directory} -Dtype={entity-type} [-Dsysid={entity-identifier}]
dataImport - Adds to or updates the portal database for the entities defined in the specified XML file(s). Requires -Dfile={path-to-file} or -Ddir={path-to-directory}
dataInit - Drop and recreate uPortal tables and reimport data
dataList - With no arguments (-Dtype={entity-type}) lists all supported portal data types and the operations (export, delete) supported for each.
```
src: https://github.com/uPortal-Project/uPortal-start/blob/master/overlays/uPortal/build.gradle

2024-10-03 05:01 UTC, 555vedant commented
@jonathanmtran Changes done.

2024-10-05 21:52 UTC, jonathanmtran commented on docs/import_export/README.md
> +- **dataImport**: Adds to or updates the portal database for the entities defined in the specified XML file(s). Requires -Dfile={path-to-file} or -Ddir={path-to-directory}
```suggestion
- **dataImport**: Adds to or updates the portal database for the entities defined in the specified XML file(s). Requires `-Dfile={path-to-file}` or `-Ddir={path-to-directory}`
```

2024-10-05 21:52 UTC, jonathanmtran commented on docs/import_export/README.md
> +- **dataList**: With no arguments (-Dtype={entity-type}) lists all supported portal data types and the operations (export, delete) supported for each.
```suggestion
- **dataList**: With no arguments (`-Dtype={entity-type}`) lists all supported portal data types and the operations (export, delete) supported for each.
```

2024-10-05 21:52 UTC, jonathanmtran commented on docs/import_export/README.md
> +- **dataExport**: Creates XML files representing the requested entities and writes them to the specified file system location. Parameters: -Ddir={path-to-directory} -Dtype={entity-type} [-Dsysid={ent
```suggestion
- **dataExport**: Creates XML files representing the requested entities and writes them to the specified file system location. Parameters: `-Ddir={path-to-directory}` `-Dtype={entity-type}` `[-Dsysid={entity-identifier}]`
```

2024-10-05 21:52 UTC, jonathanmtran commented on docs/import_export/README.md
> +- **dataDelete**: Deletes the specified entity. Requires -Dtype={entity-type} and -Dsysid={id}
```suggestion
- **dataDelete**: Deletes the specified entity. Requires `-Dtype={entity-type}` and `-Dsysid={id}`
```

2024-10-05 21:52 UTC, jonathanmtran commented on docs/import_export/README.md
> +Logs for Import/Export operations can be found in the `UPORTAL_ROOT/target/data-import-reports` directory. Look for `data-import.txt` for summary reports. If errors occur, individual error report fil
```suggestion
Logs for Import/Export operations can be found in the `uPortal-start/overlays/uPortal/build/data-import-reports` directory. Look for `data-import.txt` for summary reports. If errors occur, individual error report files will also be generated for each failed object.
```

2024-10-05 21:52 UTC, jonathanmtran commented on docs/import_export/README.md
> +To run the Import/Export tool via Gradle, navigate to the uPortal project directory and execute
```suggestion
To run the Import/Export tool via Gradle, execute the following from uPortal-start
```

Interestingly, the tasks are not available in this repo, but in the uPortal-start repo

2024-10-08 04:30 UTC, 555vedant commented
@jonathanmtran PR ready to merge ??

2024-10-09 03:55 UTC, jonathanmtran commented
Please squash the commits into one

2024-10-09 04:58 UTC, 555vedant commented
@jonathanmtran squashing done

2024-10-09 05:05 UTC, jonathanmtran approved these changes

2024-10-09 05:05 UTC, merged