Adopt uPortal CSS Variables for Web Components to Simplify Skin Management
uPortal-Project/uPortal pull request #2860
Opened 2024-10-03 19:07 UTC by 555vedant

currently, web components require individual CSS variiables to be defined separately, which adds complexity when integrating with uPortal skins. To streamline styling and ensure consistency, uPortal CSS variables (like those used for portlets) should be directly exposed and defined. This will allow web components to inherit styles such as header text color, content background color, and more, from the uPortal skin without requiring redundant definitions. The solution involves defining key CSS variables in the :root scope that web components can automatically use, improving maintainability and reducing duplication

2024-10-05 19:02 UTC, 555vedant commented
@jonathanmtran sir please tell me is there any improvement or suggestion for this PR because from 10th i have MIDSEM exam of college.

2024-10-05 21:38 UTC, jonathanmtran requested changes
In the enhancement request two examples were given.

```css
:root {
   --portlet-header-text-color: #000000
   --portlet-content-bg-color: #d0d0d0
...
}
```
`--portlet-header-text-color` would correspond to `@portlet-titlebar-link-color` found in https://github.com/uPortal-Project/uPortal/blob/HEAD/uPortal-webapp/src/main/webapp/media/skins/respondr/common/less/content.less#L165
```less
    > a {
      color: @portlet-titlebar-link-color;

      &:hover {
        color: darken(@portlet-titlebar-link-color, 20%);
      }
    }
```
The end result would be an appropriate modification that would include something like the following:
NOTE: I did **not** try this so I am not sure if this would even compile/work
```less
:root {
  --uP-portlet-header-text-color: @portlet-titlebar-link-color;
}
```

2024-10-06 13:12 UTC, 555vedant commented
@jonathanmtran is it fine ?

2024-10-08 04:30 UTC, 555vedant commented
@jonathanmtran PR ready to merge ??

2024-10-09 05:40 UTC, jonathanmtran commented
I do not feel that this PR is ready to merge.

- The modifications were made to `autosuggest.css` which is NOT a file that is related to what I feel the enhancement would be
- The UNTESTED fragment I provided contains a LESS variable. Since the modified file is not a `.less` file, it would never be compiled into CSS at build time. Therefore, the changes need to be made to the appropriate file, pre-existing or new

2024-10-09 06:36 UTC, 555vedant commented
@jonathanmtran i also noticed the same problem with less variables we cant do without less , now whats the solution for this PR ??

2024-10-11 00:13 UTC, jonathanmtran commented
I have already described my guess as to what an implementation could look like.

In order to make meaningful progress on implementing this enhancement and if you have not set up an instance of uPortal: you should set up an instance of uPortal via [uPortal-start](https://github.com/uPortal-Project/uPortal-start) and work on this.

2026-04-22 17:10 UTC, bjagg commented
Hi @555vedant — thank you for tackling #2351. Closing this PR as stale, but leaving a concrete summary so either you or another contributor has a clear path forward.

## What's structurally wrong

The core issue is a **LESS vs CSS mix-up**. uPortal's skins use [LESS](https://lesscss.org/), which is compiled to plain CSS at build time by Gradle. LESS variables like `@portlet-titlebar-link-color` only have meaning inside `.less` files — the LESS compiler substitutes them with concrete values during the build.

This PR writes the mapping into a `.css` file:

```css
:root {
    --portlet-header-text-color: @portlet-titlebar-link-color;
}
```

That file doesn't go through the LESS pipeline, so the literal string `@portlet-titlebar-link-color` is shipped to the browser as an invalid CSS value and the custom property ends up unusable. The intent of #2351 is to bridge LESS (build-time, skin authoring) and CSS custom properties (runtime, web-component consumption); that bridge has to live on the LESS side.

Two related problems in the same file:

1. `color: darken(var(--portlet-header-text-color), 20%)` — `darken()` is a LESS function; browsers don't know it, so this rule is broken at runtime.
2. Changing `border-bottom: 1px solid #efefef` to `1px solid var(--portlet-header-text-color)` replaces a light separator color with a dark link color. That's a visual regression, not an adoption of the variable.

## What acceptance would look like

1. **Put the `:root` declaration in a `.less` file under the skin**, not in a feature-specific `.css` file. As @jonathanmtran pointed out, a good place is something like `uPortal-webapp/src/main/webapp/media/skins/respondr/common/less/` — somewhere that every page loads, so the `:root` custom properties are truly global.
2. **Write it as LESS**, so the compiler substitutes the value at build time:
   ```less
   :root {
     --uP-portlet-header-text-color: @portlet-titlebar-link-color;
     --uP-portlet-content-bg-color: @portlet-content-bg-color; // or whatever the source LESS var is
   }
   ```
   The browser receives concrete colors, and web-components can then read them via `var(--uP-portlet-header-text-color)`.
3. **Use the new custom properties only in places where it's the intent** — don't repurpose unrelated existing color declarations as test sites. The goal is *exposure*, not repainting the app.
4. **Prefix the custom properties** (e.g., `--uP-...` per Jonathan's suggestion) to avoid collisions with skins or downstream web-components defining their own variables.
5. **Verify by running `./gradlew` and inspecting the compiled CSS** — the `:root` block should contain concrete hex values, not `@...` tokens.

Thanks for the interest in uPortal — #2351 is still a worthwhile improvement if you or someone else wants to pick it up along the lines above.

2026-04-22 17:11 UTC, closed without merging