Added OIDC and OAuth 2.0 issue(#2587)
uPortal-Project/uPortal pull request #2862
Opened 2024-10-11 14:14 UTC by 555vedant

this pull request outlines OIDC and OAuth 2.0  doc implementation in uPortal. It covers OIDC endpoints, group and claims filters, and OAuth endpoint usage for clients, aiding developers in secure user authentication and profile information retrieval.

Key features:

1)Detailed descriptions and examples of OIDC endpoints.

2)Configuration for group and claims filters.

3)Client registration and scope definitions.

4)Security considerations for token management.

References:

1)Official OIDC and OAuth 2.0 specifications.

2)uPortal documentation links.

2024-10-13 12:07 UTC, 555vedant commented
Sir , please once can you review this PR ??

2024-10-16 06:32 UTC, 555vedant commented
@ChristianMurphy sir please once review this PR and pls suggest changes if there ?

2024-10-18 01:42 UTC, jonathanmtran requested changes
There is documentation for endpoints that do not exist in uPortal ...

Did you actually test the endpoints to see if uPortal responds as expected?

2024-10-18 01:42 UTC, jonathanmtran commented on docs/OIDC_OAuth/README.md
> +    GET /uPortal/api/v5-1/oauth/authorize?response_type=code&client_id={client_id}&redirect_uri={redirect_uri}&scope=openid&state={state}&claims={custom_claims}
This endpoint does not exist

2024-10-18 01:42 UTC, jonathanmtran commented on docs/OIDC_OAuth/README.md
> +    POST /uPortal/api/v5-1/oauth/token
This endpoint does not exist

2024-10-18 01:42 UTC, jonathanmtran commented on docs/OIDC_OAuth/README.md
> +    GET /uPortal/api/v5-1/oauth/logout?post_logout_redirect_uri={redirect_uri}&id_token_hint={id_token}
This endpoint does not exist

2024-10-18 01:42 UTC, jonathanmtran commented on docs/OIDC_OAuth/README.md
> +    GET /uPortal/api/v5-1/oauth/authorize?response_type=code&client_id={client_id}&redirect_uri={redirect_uri}&scope=openid&claims={"userinfo":{"user_id":{"essential":true},"roles":{"values":["studen
This endpoint does not exist

2024-10-18 01:42 UTC, jonathanmtran commented on docs/OIDC_OAuth/README.md
> +    POST /uPortal/api/v5-1/oauth/token
This endpoint does not exist

2024-10-18 01:42 UTC, jonathanmtran commented on docs/OIDC_OAuth/README.md
> +    GET /uPortal/api/v5-1/oauth/userinfo
This endpoint does not exist

2024-10-18 01:42 UTC, jonathanmtran commented on docs/OIDC_OAuth/README.md
> +    GET /uPortal/api/v5-1/oauth/userinfo
The path is incorrect

2024-10-19 17:05 UTC, 555vedant commented
@jonathanmtran sir please can you provide me some resources  from whom i can make endpoints and path correctly ??

2024-10-22 20:53 UTC, ChristianMurphy commented
> sir please can you provide me some resources from whom i can make endpoints and path correctly ??

@555vedant The actual API provide swagger docs, follow @jonathanmtran's recommendation here 
https://github.com/uPortal-Project/uPortal/pull/2860#issuecomment-2406263404 to spin up uPortal-start

The swagger API can be switched on with https://uportal-project.github.io/uPortal/developer/other/API.html

2026-04-22 17:11 UTC, bjagg commented
Hi @555vedant — thank you for taking on the OIDC/OAuth docs request (#2587). Closing this PR as stale, with a summary of what would be needed for a useful replacement.

## The core issue

As @jonathanmtran flagged (7 inline comments), the endpoints documented here do not exist in uPortal. Examples:

- `/uPortal/api/v5-1/oauth/authorize`
- `/uPortal/api/v5-1/oauth/token`
- `/uPortal/api/v5-1/oauth/userinfo`
- `/uPortal/api/v5-1/oauth/logout`

These look plausible — they match typical OIDC provider conventions — but uPortal's actual OIDC/OAuth surface is different. Documentation of endpoints that don't exist is worse than none because it actively misleads integrators trying to wire services against uPortal: their requests 404, they waste time debugging configuration, and they lose trust in the project's docs generally.

## What acceptance would require

A useful OIDC/OAuth doc needs to start from the code, not from what typical OIDC providers look like. Concretely:

1. **Find the actual endpoints in uPortal.** Search for OAuth/OIDC-related Spring controllers and filters. Good starting points:
   - `grep -rn '@RequestMapping' uPortal-*/src/main/java | grep -i 'oauth\|oidc'`
   - Security configuration under `uPortal-security/`
   - Look at `org.apereo.portal.soffit.connector` and `org.apereo.portal.security.oauth` packages (if they exist — confirm first)
2. **Test each endpoint against a running uPortal** (via `uPortal-start`). Confirm the actual paths, methods, parameters, request/response shapes, and error behaviors. Screenshots or `curl` examples from real runs belong in the doc.
3. **Describe what uPortal actually supports**, including what it *doesn't* — e.g., if uPortal acts as an OIDC provider but not a relying party (or vice versa), say so. If certain standard OIDC endpoints aren't implemented, call that out explicitly so integrators know.
4. **Cover the real integration points** the issue asked for: group/claims filters and their configuration properties, OAuth client registration in uPortal, scope definitions as they actually exist in the codebase.
5. **Start with an issue comment**, not a PR, if you're unsure of scope. Post findings on #2587 first to get confirmation on the approach before writing the doc. That avoids investing effort in content that doesn't match the maintainers' intent.

Thanks again for the effort. #2587 is still open — a grounded version of this doc would be a valuable contribution.

2026-04-22 17:11 UTC, closed without merging